### ISSUE TITLE
ValueError: invalid literal

### ISSUE THREAD

**Issue by fcichos** [Molecular-Nanophotonics/TrackerLab#1]
When trying to run TrackerLab on OSX 10.14 in python 3.6 I get the following error:

Traceback (most recent call last):
  File "TrackerLab.py", line 826, in <module>
    window = Window()
  File "TrackerLab.py", line 69, in __init__
    self.restoreSettings()
  File "TrackerLab.py", line 765, in restoreSettings
    self.csv = int(self.settings.value('Settings/CSV', '0'))
ValueError: invalid literal for int() with base 10: 'false'

**Comment by fraem24** [comment]
Can be fixed deleting the INI file.
